language: node_js
node_js:
- '8'
services:
- docker
addons:
  chrome: stable
install:
- yarn
- yarn lint
- yarn build
cache:
  yarn: true
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
