language: node_js
node_js:
- '8'
services:
- docker
addons:
  chrome: stable
install:
- yarn
- yarn lint
- yarn build
- yarn docker
cache:
  yarn: true
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
deploy:
  - provider: cloudfoundry
    api: https://api.run.pivotal.io
    username: david.ahern26@gmail.com
    password:
      secure: lsboqnPb/zmLDPXtj4MZbc5zcwPJiMX9mUfvp5JxJOHQ2OWqr6egViTSEqS01d6ez6SBZcmd9QqaPFIvDTe4/ncYNOQ68+kbGYQE+XnQTuKRt9AyzGkjasXggbdLWlIvFvoJpmmZJHrggWOlWK5CkiVhTrcclLXC9X2xlXwoPiYh9BntagCLkUC2N7F8klqCkEMHjCtLp8GqXqST8uykwv2CZ7i8EDH0u+6iiSFl8oYkgPEBVWZmeCcgpdTrpxJHSw25axEb4rS8aikNtOIMyNPYSFqDfgn4OZLsxNavBf0pjwhy1yGRbU26nxd9WLMU0FFI0iurfi8Ufe8zwIfYs5gEeS6gWlQAKhTXcWRKRAiSr46MCq0yIJi/ueW0p6W4srANScqLcQTe8mmYFfFtF3D32WKab1pJvtnue/vtqhI89grM4tEBOJ7BwcheRTaOgQEQY20V5Dn7B3QJu6fV9qB2bd4nWdsfsTnUCFLyzj2sLZn4Uix9RgCEMUZnvdXJ/UcjeAhvofOAC1wgMzegV6+3hHbAGu42fcLVRPWPyZJEOQGFinnqzH/AqHsF5/68CkSlh3+MaT2b6j4nOJigtk3WZYE6/oGRwfxlqVq4i8CZ5nkJ4s19/FWvi3u5F1LBcMUj4UHwOdN/z0tmSf7BBtSTVuullyX64BBoeKCytvo=
    organization: thor
    space: dev
    on:
      repo: msc-blog-assignment/msc-blog-ui
      branch: master
  - provider: script
    script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && yarn docker:tag && yarn docker:push
    on:
      branch: master
