version: '3'

services:

  gateway:
    image: mscblog/gateway:latest
    ports:
      - 3000:8080
    environment:
      USER_API: http://user-api:3000
      GRAPHQL: http://graphql:3030
      UI_URL: http://0.0.0.0:4200
    networks:
      - main
    command: >
      /bin/bash -c "sleep 5; node ."

  graphql:
    image: mscblog/graphql:latest
    ports:
      - 3001:3030
    environment:
      USER_API: mscblog-user-api:3002
      ARTICLE_API: mscblog-article-api:3003
    networks:
      - main
    command: >
      /bin/bash -c "sleep 5; node ."

  user-api:
    image: mscblog/user-api:latest
    ports:
      - 3002:3000
    networks:
      - main
    command: >
      /bin/bash -c "sleep 5; node ."

  article-api:
    image: mscblog/article-api:latest
    ports:
      - 3003:3000
    networks:
      - main
    command: >
      /bin/bash -c "sleep 5; node ."

networks:
  main:

volumes:
  yarn:
