version: '3'

services:

  gateway:
    image: mscblog/gateway:latest
    ports:
      - 3000:8080
    environment:
      USER_API: http://user-api:3000
      GRAPHQL: http://graphql:3030
      UI_URL: http://localhost:4200
    networks:
      - main
    command: >
      /bin/bash -c "sleep 5; node ."

  consul:
    image: mscblog/consul:latest
    ports:
      - 5300:8080
    networks:
      - main

  user-api:
    image: mscblog/user-api:latest
    ports:
      - 3001:3000
    environment:
      SERVICE_DISCOVERY_HOST: ${consul_host}
      SERVICE_DISCOVERY_PORT: ${consul_port}
      HOSTNAME: user-api:3000
    networks:
      - main
    command: >
      /bin/bash -c "sleep 5; node ."

  article-api:
    image: mscblog/article-api:latest
    ports:
      - 3002:3000
    environment:
      SERVICE_DISCOVERY_HOST: ${consul_host}
      SERVICE_DISCOVERY_PORT: ${consul_port}
      HOSTNAME: article-api:3000
    networks:
      - main
    command: >
      /bin/bash -c "sleep 5; node ."

  comments-api:
    image: mscblog/comments-api:latest
    ports:
      - 3003:3000
    environment:
      SERVICE_DISCOVERY_HOST: ${consul_host}
      SERVICE_DISCOVERY_PORT: ${consul_port}
      HOSTNAME: comments-api:3000
    networks:
      - main
    command: >
      /bin/bash -c "sleep 5; node ."

  graphql:
      image: mscblog/graphql:latest
      ports:
        - 3004:3030
      environment:
        SERVICE_DISCOVERY_HOST: ${consul_host}
        SERVICE_DISCOVERY_PORT: ${consul_port}
        HOSTNAME: graphql:3030
      networks:
        - main
      command: >
        /bin/bash -c "sleep 10; node ."

networks:
  main:
